version: "3.8"
services:
  node-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/shopdb

  mongo-db:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
